goog.module('org.gwtproject.user.client.ui.DialogBox');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.safehtml.client.HasSafeHtml');
goog.require('org.gwtproject.user.client.ui.DecoratedPopupPanel');
goog.require('org.gwtproject.user.client.ui.HasHTML');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.Spliterator');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.dom.client.Document.$Overlay');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.NativeEvent.$Overlay');
goog.require('org.gwtproject.dom.client.Node.$Overlay');
goog.require('org.gwtproject.event.dom.client.MouseDownEvent');
goog.require('org.gwtproject.event.dom.client.MouseMoveEvent');
goog.require('org.gwtproject.event.dom.client.MouseOutEvent');
goog.require('org.gwtproject.event.dom.client.MouseOverEvent');
goog.require('org.gwtproject.event.dom.client.MouseUpEvent');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.safehtml.shared.SafeHtml');
goog.require('org.gwtproject.safehtml.shared.SafeHtmlUtils');
goog.require('org.gwtproject.user.client.DOM');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.Event.NativePreviewEvent');
goog.require('org.gwtproject.user.client.ui.DialogBox.$1');
goog.require('org.gwtproject.user.client.ui.DialogBox.Caption');
goog.require('org.gwtproject.user.client.ui.DialogBox.CaptionImpl');
goog.require('org.gwtproject.user.client.ui.DialogBox.MouseHandler');
goog.require('org.gwtproject.user.client.ui.UIObject');
goog.require('org.gwtproject.user.client.ui.Widget');
goog.require('org.gwtproject.user.window.client.Window');
goog.require('vmbootstrap.Asserts');

const DialogBox = goog.require('org.gwtproject.user.client.ui.DialogBox$impl');
exports = DialogBox; 