goog.module('org.gwtproject.user.client.ui.MenuBar');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.event.logical.shared.CloseHandler');
goog.require('org.gwtproject.event.logical.shared.HasCloseHandlers');
goog.require('org.gwtproject.user.client.ui.HasAnimation');
goog.require('org.gwtproject.user.client.ui.Widget');
goog.require('java.lang.IndexOutOfBoundsException');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.aria.client.Id');
goog.require('org.gwtproject.aria.client.Roles');
goog.require('org.gwtproject.core.client.Scheduler');
goog.require('org.gwtproject.core.client.Scheduler.ScheduledCommand');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.NativeEvent.$Overlay');
goog.require('org.gwtproject.dom.client.Node.$Overlay');
goog.require('org.gwtproject.dom.client.Style.$Overlay');
goog.require('org.gwtproject.event.dom.client.BlurEvent');
goog.require('org.gwtproject.event.dom.client.KeyCodes');
goog.require('org.gwtproject.event.logical.shared.CloseEvent');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.i18n.client.LocaleInfo');
goog.require('org.gwtproject.safehtml.shared.SafeHtml');
goog.require('org.gwtproject.user.client.DOM');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.ui.AbstractImagePrototype');
goog.require('org.gwtproject.user.client.ui.FocusPanel');
goog.require('org.gwtproject.user.client.ui.MenuBar.$1');
goog.require('org.gwtproject.user.client.ui.MenuBar.$2');
goog.require('org.gwtproject.user.client.ui.MenuBar.$3');
goog.require('org.gwtproject.user.client.ui.MenuBar.MenuPopup');
goog.require('org.gwtproject.user.client.ui.MenuBar.Resources');
goog.require('org.gwtproject.user.client.ui.MenuBar_ResourcesImpl');
goog.require('org.gwtproject.user.client.ui.MenuItem');
goog.require('org.gwtproject.user.client.ui.MenuItemSeparator');
goog.require('org.gwtproject.user.client.ui.PopupPanel');
goog.require('org.gwtproject.user.client.ui.UIObject');
goog.require('vmbootstrap.Asserts');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Exceptions');

const MenuBar = goog.require('org.gwtproject.user.client.ui.MenuBar$impl');
exports = MenuBar; 