goog.module('org.gwtproject.user.client.ui.PopupPanel');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.event.logical.shared.HasCloseHandlers');
goog.require('org.gwtproject.user.client.ui.HasAnimation');
goog.require('org.gwtproject.user.client.ui.SimplePanel');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.Spliterator');
goog.require('java.util.function.Consumer');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.core.client.JavaScriptObject.$Overlay');
goog.require('org.gwtproject.dom.client.Document.$Overlay');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.NativeEvent.$Overlay');
goog.require('org.gwtproject.dom.client.Node.$Overlay');
goog.require('org.gwtproject.dom.client.Style.$Overlay');
goog.require('org.gwtproject.dom.style.shared.Position');
goog.require('org.gwtproject.dom.style.shared.Unit');
goog.require('org.gwtproject.event.logical.shared.CloseEvent');
goog.require('org.gwtproject.event.logical.shared.CloseHandler');
goog.require('org.gwtproject.event.logical.shared.ResizeHandler');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.i18n.client.LocaleInfo');
goog.require('org.gwtproject.user.client.DOM');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.Event.NativePreviewEvent');
goog.require('org.gwtproject.user.client.ui.PopupPanel.$1');
goog.require('org.gwtproject.user.client.ui.PopupPanel.$2');
goog.require('org.gwtproject.user.client.ui.PopupPanel.$3');
goog.require('org.gwtproject.user.client.ui.PopupPanel.$4');
goog.require('org.gwtproject.user.client.ui.PopupPanel.AnimationType');
goog.require('org.gwtproject.user.client.ui.PopupPanel.PositionCallback');
goog.require('org.gwtproject.user.client.ui.PopupPanel.ResizeAnimation');
goog.require('org.gwtproject.user.client.ui.UIObject');
goog.require('org.gwtproject.user.client.ui.Widget');
goog.require('org.gwtproject.user.client.ui.impl.PopupImpl');
goog.require('org.gwtproject.user.history.client.History');
goog.require('org.gwtproject.user.window.client.Window');
goog.require('vmbootstrap.Asserts');
goog.require('vmbootstrap.Casts');

const PopupPanel = goog.require('org.gwtproject.user.client.ui.PopupPanel$impl');
exports = PopupPanel; 