goog.module('org.gwtproject.user.client.ui.RootPanel');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.user.client.ui.AbsolutePanel');
goog.require('java.lang.Iterable');
goog.require('java.util.HashMap');
goog.require('java.util.HashSet');
goog.require('java.util.Map');
goog.require('java.util.Set');
goog.require('java.util.Spliterator');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.core.client.JavaScriptObject.$Overlay');
goog.require('org.gwtproject.dom.client.Document.$Overlay');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.Node.$Overlay');
goog.require('org.gwtproject.event.logical.shared.CloseEvent');
goog.require('org.gwtproject.event.logical.shared.CloseHandler');
goog.require('org.gwtproject.i18n.client.BidiUtils');
goog.require('org.gwtproject.i18n.client.HasDirection.Direction');
goog.require('org.gwtproject.i18n.client.LocaleInfo');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.ui.AttachDetachException');
goog.require('org.gwtproject.user.client.ui.AttachDetachException.Command');
goog.require('org.gwtproject.user.client.ui.RootPanel.DefaultRootPanel');
goog.require('org.gwtproject.user.client.ui.Widget');
goog.require('org.gwtproject.user.window.client.Window');
goog.require('vmbootstrap.Asserts');
goog.require('vmbootstrap.Casts');

const RootPanel = goog.require('org.gwtproject.user.client.ui.RootPanel$impl');
exports = RootPanel; 