goog.module('org.gwtproject.touch.client.TouchScroller');

goog.require('java.lang.Object');
goog.require('nativebootstrap.Util');
goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('java.lang.Boolean');
goog.require('java.lang.Integer');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.core.client.Duration');
goog.require('org.gwtproject.core.client.JsArray.$Overlay');
goog.require('org.gwtproject.core.client.Scheduler');
goog.require('org.gwtproject.core.client.Scheduler.RepeatingCommand');
goog.require('org.gwtproject.dom.client.Touch.$Overlay');
goog.require('org.gwtproject.event.dom.client.TouchCancelEvent');
goog.require('org.gwtproject.event.dom.client.TouchEndEvent');
goog.require('org.gwtproject.event.dom.client.TouchEvent');
goog.require('org.gwtproject.event.dom.client.TouchMoveEvent');
goog.require('org.gwtproject.event.dom.client.TouchStartEvent');
goog.require('org.gwtproject.event.legacy.shared.EventHandler');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.touch.client.DefaultMomentum');
goog.require('org.gwtproject.touch.client.Momentum');
goog.require('org.gwtproject.touch.client.Point');
goog.require('org.gwtproject.touch.client.TouchScroller.$1');
goog.require('org.gwtproject.touch.client.TouchScroller.$2');
goog.require('org.gwtproject.touch.client.TouchScroller.$3');
goog.require('org.gwtproject.touch.client.TouchScroller.$4');
goog.require('org.gwtproject.touch.client.TouchScroller.$5');
goog.require('org.gwtproject.touch.client.TouchScroller.$6');
goog.require('org.gwtproject.touch.client.TouchScroller.MomentumCommand');
goog.require('org.gwtproject.touch.client.TouchScroller.MomentumTouchRemovalCommand');
goog.require('org.gwtproject.touch.client.TouchScroller.TemporalPoint');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.ui.HasScrolling');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Primitives');

const TouchScroller = goog.require('org.gwtproject.touch.client.TouchScroller$impl');
exports = TouchScroller; 