goog.module('org.gwtproject.user.datepicker.client.DatePicker');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.editor.client.IsEditor');
goog.require('org.gwtproject.event.logical.shared.HasHighlightHandlers');
goog.require('org.gwtproject.event.logical.shared.HasShowRangeHandlers');
goog.require('org.gwtproject.user.client.ui.Composite');
goog.require('org.gwtproject.user.client.ui.HasValue');
goog.require('java.lang.IllegalArgumentException');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.Date');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.editor.client.LeafValueEditor');
goog.require('org.gwtproject.editor.client.adapters.TakesValueEditor');
goog.require('org.gwtproject.event.logical.shared.HighlightEvent');
goog.require('org.gwtproject.event.logical.shared.HighlightHandler');
goog.require('org.gwtproject.event.logical.shared.ShowRangeEvent');
goog.require('org.gwtproject.event.logical.shared.ShowRangeHandler');
goog.require('org.gwtproject.event.logical.shared.ValueChangeEvent');
goog.require('org.gwtproject.event.logical.shared.ValueChangeHandler');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.user.client.ui.UIObject');
goog.require('org.gwtproject.user.client.ui.VerticalPanel');
goog.require('org.gwtproject.user.datepicker.client.CalendarModel');
goog.require('org.gwtproject.user.datepicker.client.CalendarUtil');
goog.require('org.gwtproject.user.datepicker.client.CalendarView');
goog.require('org.gwtproject.user.datepicker.client.DateChangeEvent');
goog.require('org.gwtproject.user.datepicker.client.DatePicker.$1');
goog.require('org.gwtproject.user.datepicker.client.DatePicker.DateHighlightEvent');
goog.require('org.gwtproject.user.datepicker.client.DatePicker.DateStyler');
goog.require('org.gwtproject.user.datepicker.client.DatePicker.StandardCss');
goog.require('org.gwtproject.user.datepicker.client.DefaultCalendarView');
goog.require('org.gwtproject.user.datepicker.client.DefaultMonthSelector');
goog.require('org.gwtproject.user.datepicker.client.MonthSelector');
goog.require('vmbootstrap.Asserts');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Exceptions');

const DatePicker = goog.require('org.gwtproject.user.datepicker.client.DatePicker$impl');
exports = DatePicker; 