goog.module('org.gwtproject.user.cellview.client.AbstractHeaderOrFooterBuilder');

goog.require('java.lang.Object');
goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.user.cellview.client.FooterBuilder');
goog.require('org.gwtproject.user.cellview.client.HeaderBuilder');
goog.require('java.lang.IllegalStateException');
goog.require('java.lang.Integer');
goog.require('java.lang.Math');
goog.require('java.lang.String');
goog.require('java.lang.UnsupportedOperationException');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.cell.client.Cell.Context');
goog.require('org.gwtproject.dom.builder.shared.ElementBuilderBase');
goog.require('org.gwtproject.dom.builder.shared.HtmlBuilderFactory');
goog.require('org.gwtproject.dom.builder.shared.HtmlTableSectionBuilder');
goog.require('org.gwtproject.dom.builder.shared.TableRowBuilder');
goog.require('org.gwtproject.dom.builder.shared.TableSectionBuilder');
goog.require('org.gwtproject.dom.client.Document.$Overlay');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.TableRowElement.$Overlay');
goog.require('org.gwtproject.dom.style.shared.Position');
goog.require('org.gwtproject.dom.style.shared.Unit');
goog.require('org.gwtproject.i18n.client.LocaleInfo');
goog.require('org.gwtproject.safehtml.shared.SafeHtml');
goog.require('org.gwtproject.safehtml.shared.SafeHtmlBuilder');
goog.require('org.gwtproject.safehtml.shared.SafeHtmlUtils');
goog.require('org.gwtproject.user.cellview.client.AbstractCellTable');
goog.require('org.gwtproject.user.cellview.client.AbstractHeaderOrFooterBuilder.TwoWayHashMap');
goog.require('org.gwtproject.user.cellview.client.Column');
goog.require('org.gwtproject.user.cellview.client.Header');
goog.require('org.gwtproject.user.client.ui.AbstractImagePrototype');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Exceptions');
goog.require('vmbootstrap.Primitives');

const AbstractHeaderOrFooterBuilder = goog.require('org.gwtproject.user.cellview.client.AbstractHeaderOrFooterBuilder$impl');
exports = AbstractHeaderOrFooterBuilder; 