goog.module('org.gwtproject.user.client.ui.CustomScrollPanel');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.user.client.ui.ScrollPanel');
goog.require('java.lang.Iterable');
goog.require('java.util.Spliterator');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.core.client.Duration');
goog.require('org.gwtproject.core.client.Scheduler');
goog.require('org.gwtproject.dom.client.Document.$Overlay');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.Node.$Overlay');
goog.require('org.gwtproject.dom.client.Style.$Overlay');
goog.require('org.gwtproject.dom.style.shared.Overflow');
goog.require('org.gwtproject.dom.style.shared.Unit');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.layout.client.Layout');
goog.require('org.gwtproject.layout.client.Layout.Layer');
goog.require('org.gwtproject.resources.client.CommonResources');
goog.require('org.gwtproject.user.client.DOM');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.ui.AbstractNativeScrollbar');
goog.require('org.gwtproject.user.client.ui.AttachDetachException');
goog.require('org.gwtproject.user.client.ui.CustomScrollPanel.$1');
goog.require('org.gwtproject.user.client.ui.CustomScrollPanel.$2');
goog.require('org.gwtproject.user.client.ui.CustomScrollPanel.$3');
goog.require('org.gwtproject.user.client.ui.CustomScrollPanel.Resources');
goog.require('org.gwtproject.user.client.ui.CustomScrollPanel_ResourcesImpl');
goog.require('org.gwtproject.user.client.ui.HorizontalScrollbar');
goog.require('org.gwtproject.user.client.ui.IsWidget');
goog.require('org.gwtproject.user.client.ui.NativeHorizontalScrollbar');
goog.require('org.gwtproject.user.client.ui.NativeHorizontalScrollbar_ResourcesImpl');
goog.require('org.gwtproject.user.client.ui.NativeVerticalScrollbar');
goog.require('org.gwtproject.user.client.ui.NativeVerticalScrollbar_ResourcesTransparantImpl');
goog.require('org.gwtproject.user.client.ui.ResizeLayoutPanel.Impl');
goog.require('org.gwtproject.user.client.ui.ResizeLayoutPanel.Impl.Delegate');
goog.require('org.gwtproject.user.client.ui.ResizeLayoutPanel.ImplStandard');
goog.require('org.gwtproject.user.client.ui.ScrollImpl');
goog.require('org.gwtproject.user.client.ui.VerticalScrollbar');
goog.require('org.gwtproject.user.client.ui.Widget');
goog.require('vmbootstrap.Arrays');

const CustomScrollPanel = goog.require('org.gwtproject.user.client.ui.CustomScrollPanel$impl');
exports = CustomScrollPanel; 