goog.module('org.gwtproject.user.client.ui.ValueBoxBase');

goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.editor.client.IsEditor');
goog.require('org.gwtproject.event.dom.client.HasChangeHandlers');
goog.require('org.gwtproject.i18n.client.AutoDirectionHandler.Target');
goog.require('org.gwtproject.i18n.shared.HasDirectionEstimator');
goog.require('org.gwtproject.user.client.ui.FocusWidget');
goog.require('org.gwtproject.user.client.ui.HasName');
goog.require('org.gwtproject.user.client.ui.HasText');
goog.require('org.gwtproject.user.client.ui.HasValue');
goog.require('java.lang.IndexOutOfBoundsException');
goog.require('java.lang.String');
goog.require('java.text.ParseException');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.NativeEvent.$Overlay');
goog.require('org.gwtproject.dom.client.Style.$Overlay');
goog.require('org.gwtproject.editor.ui.client.adapters.ValueBoxEditor');
goog.require('org.gwtproject.event.dom.client.ChangeEvent');
goog.require('org.gwtproject.event.dom.client.ChangeHandler');
goog.require('org.gwtproject.event.logical.shared.ValueChangeEvent');
goog.require('org.gwtproject.event.logical.shared.ValueChangeHandler');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.gwtproject.i18n.client.AutoDirectionHandler');
goog.require('org.gwtproject.i18n.client.BidiPolicy');
goog.require('org.gwtproject.i18n.client.BidiUtils');
goog.require('org.gwtproject.i18n.client.HasDirection.Direction');
goog.require('org.gwtproject.i18n.shared.DirectionEstimator');
goog.require('org.gwtproject.text.shared.Parser');
goog.require('org.gwtproject.text.shared.Renderer');
goog.require('org.gwtproject.user.client.DOM');
goog.require('org.gwtproject.user.client.Event');
goog.require('org.gwtproject.user.client.ui.ValueBoxBase.TextAlignment');
goog.require('org.gwtproject.user.client.ui.impl.TextBoxImpl');
goog.require('vmbootstrap.Exceptions');

const ValueBoxBase = goog.require('org.gwtproject.user.client.ui.ValueBoxBase$impl');
exports = ValueBoxBase; 