goog.module('org.elemento.EventType');

goog.require('java.lang.Object');
goog.require('nativebootstrap.Util');
goog.require('elemental2.dom.ClipboardEvent.$Overlay');
goog.require('elemental2.dom.Document.$Overlay');
goog.require('elemental2.dom.DragEvent.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.EventListener.$Overlay');
goog.require('elemental2.dom.EventTarget.$Overlay');
goog.require('elemental2.dom.FocusEvent.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HashChangeEvent.$Overlay');
goog.require('elemental2.dom.KeyboardEvent.$Overlay');
goog.require('elemental2.dom.MessageEvent.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.PageTransitionEvent.$Overlay');
goog.require('elemental2.dom.PopStateEvent.$Overlay');
goog.require('elemental2.dom.TouchEvent.$Overlay');
goog.require('elemental2.dom.UIEvent.$Overlay');
goog.require('elemental2.dom.WheelEvent.$Overlay');
goog.require('elemental2.dom.Window.$Overlay');
goog.require('elemental2.webstorage.StorageEvent.$Overlay');
goog.require('jsinterop.base.Js');
goog.require('org.elemento.EventType.$LambdaAdaptor$1');
goog.require('org.elemento.EventType.$LambdaAdaptor$2');
goog.require('org.elemento.IsElement');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('vmbootstrap.Casts');

const EventType = goog.require('org.elemento.EventType$impl');
exports = EventType; 