goog.module('org.gwtproject.cell.client.IconCellDecorator');

goog.require('java.lang.Object');
goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.cell.client.Cell');
goog.require('java.lang.Math');
goog.require('java.lang.String');
goog.require('java.util.Set');
goog.require('nativebootstrap.Equality');
goog.require('org.gwtproject.cell.client.Cell.Context');
goog.require('org.gwtproject.cell.client.IconCellDecorator.Template');
goog.require('org.gwtproject.cell.client.ValueUpdater');
goog.require('org.gwtproject.core.client.JavaScriptObject.$Overlay');
goog.require('org.gwtproject.dom.client.Element.$Overlay');
goog.require('org.gwtproject.dom.client.NativeEvent.$Overlay');
goog.require('org.gwtproject.dom.client.Node.$Overlay');
goog.require('org.gwtproject.i18n.client.LocaleInfo');
goog.require('org.gwtproject.resources.client.ImageResource');
goog.require('org.gwtproject.safecss.shared.SafeStyles');
goog.require('org.gwtproject.safecss.shared.SafeStylesBuilder');
goog.require('org.gwtproject.safecss.shared.SafeStylesUtils');
goog.require('org.gwtproject.safehtml.shared.SafeHtml');
goog.require('org.gwtproject.safehtml.shared.SafeHtmlBuilder');
goog.require('org.gwtproject.safehtml.shared.SafeHtmlUtils');
goog.require('org.gwtproject.user.client.ui.AbstractImagePrototype');
goog.require('org.gwtproject.user.client.ui.HasVerticalAlignment');
goog.require('org.gwtproject.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Primitives');

const IconCellDecorator = goog.require('org.gwtproject.cell.client.IconCellDecorator$impl');
exports = IconCellDecorator; 